# Generated by Django 3.1.2 on 2020-10-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
